[tool.pytest.ini_options]
addopts = [
    "--html=reports/report.html",
    "--self-contained-html",
    "--cov=bank",
    "--cov-report=html:reports/coverage/",
    "--cov-report=term",
]
testpaths = ["tests"]
python_files = ["test_*.py"]


[tool.black]
line-length = 119
