[tool.pytest.ini_options]
addopts = [
    "--html=reports/report.html",
    "--self-contained-html",
    "--cov=bank",
    "--cov-report=html:reports/coverage/",
    "--cov-report=term",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
base_url = "https://www.python.org"


[tool.black]
line-length = 119

[tool.poetry]
name = "python-testing"
version = "0.1.0"
description = ""
authors = ["Miroslav Biňas <miroslav.binas@tuke.sk>"]
readme = "README.md"
packages = [{include = "python_testing"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
requests = "^2.28.1"
jsonschema = "^4.17.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-html = "^3.2.0"
pytest-cov = "^4.0.0"
pytest-base-url = "^2.0.0"
ipython = "^8.6.0"
black = "^22.10.0"
Faker = "^15.1.3"
selenium = "^4.6.0"
httpie = "^3.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
